language: generic
matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial
          before_install:
            - sudo apt-get -y install doxygen graphviz
            - pip install --user cpp-coveralls
            - sudo apt install -y nodejs
            - sudo apt install -y npm
            - sudo npm install -g cspell@4.0.38
          script:
            - cd projects/hello_world/
            - make presubmit
            - make spellcheck
            - make find-missing-tests
            - make find-unused-tests
            - cd ../../tools/
            - ./generate_doxygen_docs.sh
          after_success:
            - cd ../
            - coveralls --gcov "gcov-8"
              --include "library/L0_Platform"
              --include "library/L1_Peripheral"
              --include "library/L2_HAL"
              --include "library/L3_Application"
              --include "library/utility"
          deploy:
            provider: pages
            skip-cleanup: true
            github-token: $GITHUB_TOKEN
            keep-history: true
            on:
              branch: master
        - os: osx
          osx_image: xcode10
          before_install:
            - pip install --user cpp-coveralls
          script:
            - cd projects/hello_world/
            - make presubmit
        - os: osx
          osx_image: xcode11.3
          before_install:
            - pip install --user cpp-coveralls
          script:
            - cd projects/hello_world/
            - make presubmit
install: ./setup

