# Project Information
site_name: SJSU-DEV2
# Configuration
theme:
  name: 'material'
  # custom_dir: css/
  # include_sidebar: true
  highlightjs: true
  hljs_style:
    - monokai
  extra_css:
    - css/extra.css

docs_dir: documentation/

# Copyright
copyright: 'Copyright (C) 2018-2019 San Jose State University Computer Engineering Department'

#Navigation
nav:
  - Home: 'index.md'
  - Get Started:
        - Getting started: 'getting-started/getting-started.md'
        - How to Use Make: 'getting-started/using-make.md'
  #- 'guides-toc.md'
  - Guides:
        - Understanding The Library Directory Layout: 'guides/understanding-the-platforms-layout.md'
        - Unit Testing Your Project: 'guides/unit-testing.md'
        - Debugging with OpenOCD and GDB: 'guides/debugging-with-openocd-gdb.md'
        - Telemetry Embedded Runtime Monitoring and Tuning: 'guides/telemetry-runtime-monitoring-and-tuning.md'

  - 'contributing-toc.md'
  - 'about.md'
  - 'copyrights.md'

markdown_extensions:
  - admonition
  - pymdownx.mark # highlighting
  - pymdownx.superfences # nest code
  - codehilite # code syntax coding
  - toc:
      permalink:
